### ISSUE TITLE
Request for allowing to change licence

### ISSUE THREAD

**Issue by aNeutrino** [lizardfs/lizardfs-docker-volume-plugin#1]
@zicklag we have forked your repository because you made 100% of first version and this is great job.

however in our project we use different licence GPLv3, it is because we do not want that anyone ever will take our code and close it, do you agree that in our fork we will continue with GPLv3 licence, and if any merge request will be initiated to your repository from us we automatically agree that it became compatible with your license over there which is MIT.

Please not that your all code on your repository is going to have exactly the license you set there, it is just about COPY/fork we made from you which is going to by inside of our repository. 

Please let us know your opinion.

**Comment by zicklag** [comment]
Because it is MIT licensed, the only condition for using it is keeping the original license statement along with the project source. You can put your own license above it, such as GPLv3, that will include all your changes and anything that the project becomes after that.

Does that make sense?

**Comment by jadolg** [comment]
I think it makes sense.
@aNeutrino can you take care of it?
