### ISSUE TITLE
setup CI with Travis in GitHub

### ISSUE THREAD

**Issue by aNeutrino** [lizardfs/lizardfs-docker-volume-plugin#2]
Please also advice some

- code test coverage and
- include badges and
- and make auto deployment  :)

**Comment by jadolg** [comment]
I'll track the deployment on task https://github.com/lizardfs/lizardfs-docker-volume-plugin/projects/1#card-38995295 as CI is already working.
Once we recover our organization in DockerHub this task can be done.
