### ISSUE TITLE
Migrate to Non-Fork Repo

### ISSUE THREAD

**Issue by zicklag** [lizardfs/lizardfs-docker-volume-plugin#4]
To increase discoverability on GitHub I think it would be good to migrate the repository to a standalone repository so that it will pop up in GitHub searches.

You have to contact GitHub support to have them migrate the repo: https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork.

**Comment by jadolg** [comment]
I booth like and don't like this approach as I would like the visibility but also to always show that the project was forked from you.

**Comment by jadolg** [comment]
I have just written to support. Let's wait for their answer. Maybe there's a way to make it standalone still showing it was forked from your codebase.

**Comment by zicklag** [comment]
Well, thanks for wanting to keep that visible. :) If nothing else, you could just put a note in the README somewhere.

**Comment by jadolg** [comment]
I will of course :)
I'll close this issue as support already did the work.
